[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hate-preproc"
version = "0.1.0"
dependencies = [
  "pandas",
  "numpy",
  "matplotlib",
  "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["src"]
